# Generated by Django 5.1.15 on 2026-05-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_snapshot',
            field=models.JSONField(default=dict, verbose_name='收货地址快照'),
        ),
    ]
