# Generated by Django 5.1.15 on 2026-05-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_shipping_method_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('', '无'), ('requested', '申请中'), ('approved', '已同意'), ('rejected', '已拒绝'), ('refunded', '已退款')], default='', max_length=20, verbose_name='退款状态'),
        ),
    ]
