# Generated by Django 5.1.15 on 2026-05-23 05:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(choices=[('full_reduction', '满减'), ('discount', '折扣'), ('fixed_amount', '固定金额')], max_length=20, verbose_name='优惠券类型')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠券的折扣值')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='最低订单金额要求')),
                ('start_time', models.DateTimeField(verbose_name='优惠券生效时间')),
                ('end_time', models.DateTimeField(verbose_name='优惠券失效时间')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期')], default='unused', max_length=20, verbose_name='优惠券状态')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'db_table': 'coupons_coupon',
            },
        ),
    ]
