# Generated by Django 5.1.15 on 2026-05-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('full_reduction', '满减')], max_length=20, verbose_name='优惠券类型'),
        ),
    ]
