# Generated by Django 5.1.15 on 2026-05-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sales_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='平均评分'),
        ),
    ]
